# Generated by Django 6.0 on 2026-01-06 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ScanAnalysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='scans/')),
                ('image_name', models.CharField(max_length=255)),
                ('tumour_detected', models.BooleanField(default=False)),
                ('confidence_score', models.FloatField(default=0.0)),
                ('tumour_area_pixels', models.IntegerField(default=0)),
                ('comparison_image', models.ImageField(blank=True, null=True, upload_to='scans/')),
                ('growth_percentage', models.FloatField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
